### ISSUE TITLE
Add /auth at the beginning of the URL

### ISSUE THREAD

**Issue by marc-farre** [njsubedi/cloudron-keycloak#1]
Thanks for this work, Keycloak runs perfectly!

I only have a small problem. On classic installation, the root URL starts with `/auth`.
E.g: https://keycloak.my-cloudron.tdl/auth/admin/master/console/#/realms/cloudron
Or https://keycloak.my-cloudron.tdl/auth/realms/cloudron/protocol/openid-connect/auth

But with this Keycloak installation, we do not have the `/auth`, we have:
 https://keycloak.my-cloudron.tdl/admin/master/console/#/realms/cloudron
Or https://keycloak.my-cloudron.tdl/realms/cloudron/protocol/openid-connect/auth

This is a problem with some library, e.g. https://github.com/MohammadWaleed/keycloak-admin-client which enables to easily interact with Keycloak API. It doesn't work because `/auth` is missing.

Thanks!

**Comment by njsubedi** [comment]
You can configure the client library by setting a custom URI. See https://github.com/MohammadWaleed/keycloak-admin-client#custom-keycloak-endpoints

Keycloak used to have “/auth” by default and it couldn’t be removed. That’s why many client libraries and extensions must have defaulted to the same base url. Fortunately, the current version of Keycloak (v 17.0 and newer) does not have it by default, but you can add “/auth” or anything you like by simply adding to the configuration file. See https://www.keycloak.org/server/hostname 

since all the future versions of Keycloak would run on the base “/“ instead of “/auth”, I believe many extensions will update themselves. If there’s a client library or extension, I’d send them a PR instead.

**Comment by marc-farre** [comment]
Thanks very much for your quick and detailed reply.
PR done: https://github.com/MohammadWaleed/keycloak-admin-client/issues/84
